Authentication-with-devise/config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root 'homes#index'
  devise_for :users
end

Authentication-with-devise/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Authentication-with-devise/app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
end

Authentication-with-devise/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs

end

Authentication-with-devise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Authentication-with-devise/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :info, :body)
    end
end

Authentication-with-devise/app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

Authentication-with-devise/app/helpers/application_helper.rb
module ApplicationHelper
end

Authentication-with-devise/app/helpers/blogs_helper.rb
module BlogsHelper
end

Authentication-with-devise/app/helpers/homes_helper.rb
module HomesHelper
end

Authentication-with-devise/app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :info %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Authentication-with-devise/app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

Authentication-with-devise/app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<%= link_to "Home", root_path %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.info %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Blog', new_blog_path %>
<% end %>

Authentication-with-devise/app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

Authentication-with-devise/app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @blog.info %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
  <br/>user
  <%= @blog.user_id %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

Authentication-with-devise/app/views/homes/index.html.erb
<ul
    <li> <h1> <%= link_to 'Wellcome to home', root_path %> </h1></li>
    <% if user_signed_in? %>
         <li> <%= current_user.email %> </li>
         <li> <%= link_to 'Edit user info', edit_user_registration_path %> </li>
         <li> <%= link_to 'Post new blog', new_blog_path %> </li>
        <li> <%= link_to 'Login Out', destroy_user_session_path, method: :delete %> </li>
    <% else %>
        <li> <%= link_to 'Registration', new_user_registration_path %> </li>
        <li> <%= link_to 'Login', new_user_session_path %> </li>
    <% end %>
</ul>

Authentication-with-devise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationWithDevise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"><%= alert %></p><% end %>
    <%= yield %>
  </body>
</html>